# Generated by Django 5.1.1 on 2024-09-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
