# Generated by Django 5.1.1 on 2024-09-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_subtitle_language_subtitlefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitlefile',
            name='file',
            field=models.FileField(upload_to='videos/subtitles/'),
        ),
    ]
